### ISSUE TITLE
problem: questions from mods not distinguished from answers

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#101]
problem: questions from moderators are not distinguished from answers/comments from alpplicants (non-moderators). This is a problem because applicants might not notice all of them.

solution: maybe use a different background colour or something like that and also show a symbol next to moderators names

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #103 
@emurgobot done
