### ISSUE TITLE
problem: moderators cannot delegate their vote to another moderator

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#107]
problem: some moderators have expertise in different fields. For example one moderator might be great at tech stuff and another one might be good at business stuff. The guy who's good at business stuff might want to just delegate certain types of questions to the guy who's good at tech stuff.

solution: the solution can be global for each question type rather than each individual application.

any solution should take into account that questions (on the application form) will almost certainly be edited, new questions will be added, etc. So it should be done by some kind of index rather than the text of a question.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #115.

@emurgobot done
