### ISSUE TITLE
problem: delegates don't know they are delegates

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#121]
problem: when a moderator delegates a question to another moderator, it's not clear to the other moderator that someone just delegated a question to them.

solution: display something to the moderator showing them that they have been delegated this question and by who

**Comment by anbud** [comment]
Hmm, this is how it should already look like if someone delegates you:
![image](https://i.imgur.com/7hlGOpd.png?1)

That's how it works locally. If it's not working correctly in production, I'll check out what can be the cause. :)

**Comment by gazhayes** [comment]
Ah ok, could be legacy database issues or something on production
