### ISSUE TITLE
problem: moderators can accidentally delete applications

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#123]
problem: moderators can accidentally delete applications

solution: instead of deleting applications, allow moderators to hide them (but still remain viewable to everyone else).

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - So removing it hide it for that moderator? or all? What is the purpose then of hiding it? Just so I can understander the use case :)

**Comment by gazhayes** [comment]
Make an account on production and I'll make u a moderator

**Comment by AshHimself** [comment]
What's the URL :) I am a moderator locally though. I may just be stupid :P

**Comment by gazhayes** [comment]
/moderator/applications

**Comment by AshHimself** [comment]
Fixed in #155
@emurgobot label "done"
@emurgobot done
