### ISSUE TITLE
problem: User Question can be submit without Application

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#126]
Website pop user into "User Question" after they finished "Application"(which considered as Part 1),
but user can also fill in "User Question"  without priorly finished "Application"

**Comment by gazhayes** [comment]
The exception to this is when users have been attached to an application (member of a team that already has an application).

**Comment by anbud** [comment]
I'll do this one as a part of #125.

@emurgobot claim

**Comment by anbud** [comment]
Done in #149.
