### ISSUE TITLE
problem: moderators can submit new applications and personal data

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#129]
problem: moderators can submit new applications and personal data.

Moderators never need to do this, so we can entirely remove it from their view and send them directly to /moderator/applications

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #145

**Comment by MadanBhandari** [comment]
@emurgobot done
