### ISSUE TITLE
problem: applicant can’t save their progress when filling forms

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#135]
they need to complete the whole section of the form to save their progress
but not allow to save "question by question"

<img width="604" alt="ux-no-save-for-each-question" src="https://user-images.githubusercontent.com/44600923/48391167-65676c00-e740-11e8-898c-d8e5466e2126.png">

**Comment by porcellus** [comment]
Would automatically saving every modification as they enter it be ok or do we want a save button?

**Comment by gazhayes** [comment]
I think automatic saving would be ok, maybe put like a tick or something next to the field to indicate it's been saved and has passed validation.

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Autosave is definitely better UX-wise than a save button, go for it. :)

**Comment by porcellus** [comment]
@emurgobot done in #168
