### ISSUE TITLE
problem: hamburger menu doesn't work 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#138]
<img width="784" alt="ux-humberger-dont-work" src="https://user-images.githubusercontent.com/44600923/48391690-c2642180-e742-11e8-8a9e-e2cc8dab193b.png">
no response after clicked

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #139
