### ISSUE TITLE
problem: node-sass v3.13.0 in use but too old

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#15]
problem: node-sass v3.13.0 is too old to work with node 8 and it fails in production.

solution: update to latest version of node-sass. This appears to be a dependency of fourseven:scss@3.13.0

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@samuelralak  I've fixed this in #16

**Comment by gazhayes** [comment]
Sorry I forgot to claim it before working on it!

**Comment by samuelralak** [comment]
its alright 👍
