### ISSUE TITLE
problem: nominal ratings are difficult to compare

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#153]
problem: when moderators rate answers, it's difficult for them to consider what they are really comparing it to. For example, they might think an answer is a 7, but only in comparison to many other answers they've seen before. But that means the rating should actually change in future based on future answers on new applications. This means over time, good answers could be rated lower than bad answers because a nominal rating can't take future applications into consideration.

solution: instead of using the nominal 1-10 rating system, switch over to the ELO ranking system.

This can be taken from Blockrazor where it's currently in use for ranking wallets.

I have drawn up a suggested layout but this doesn't mean it has to be used. In this layout, two applications are shown side by side and the moderator chooses the best answer from each column. They can also delegate this and ask a question, but that should probably be another issue after the skeleton is done.

![photo6296210490598205590](https://user-images.githubusercontent.com/8143945/48461106-f73cab00-e80c-11e8-9e08-c3dd508b6132.jpg)

ping @anbud this is probably for you

**Comment by anbud** [comment]
Yap, this one is fun. :)

@emurgobot claim

**Comment by anbud** [comment]
Done in #166.

The UI could probably use some love, and I'll add required tests in a separate issue. But the basic functionality is there, I've used the suggested layout and rewired delegation and commenting.

@emurgobot done
