### ISSUE TITLE
problem: error occurs when "ask questions" 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#159]
can't process comment for "ask questions" button 

an error pops up 
<img width="660" alt="error-" src="https://user-images.githubusercontent.com/44600923/48542659-b6bb5b00-e8fa-11e8-9a9b-6b96f7bb99c5.png">

**Comment by anbud** [comment]
Since I'm changing this page anyway in #153, I'll fix this there as well.

@emurgobot claim

**Comment by anbud** [comment]
Fixed in #166.

@emurgobot done
