### ISSUE TITLE
problem: no place to follow up "delegated question"

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#190]
or no emails notification sent when questions delegated to specific moderator 

therefore the delegated moderator do not know 1) he was responsible for that question 2)where to follow up batches of assigned questions

**Comment by gazhayes** [comment]
This is actually ok because when the moderator starts rating applications it tells them that this question has been delegated to them. They don't need to know ahead of time, only need to know when they start ranking the answers.
