### ISSUE TITLE
problem: application ID number is different 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#211]
the one shown within the application is different 

<img width="914" alt="screenshot 2018-12-04 at 10 34 36 am" src="https://user-images.githubusercontent.com/44600923/49415284-30838d80-f7b1-11e8-8b06-b2505136772a.png">
<img width="1295" alt="screenshot 2018-12-04 at 10 34 31 am" src="https://user-images.githubusercontent.com/44600923/49415285-30838d80-f7b1-11e8-987c-0fe6ca8e29db.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #213
