### ISSUE TITLE
Problem: incorrect form questions 

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#23]
Problem: the form questions are incorrect.

Solution: add questions based on the following spreadsheet: https://docs.google.com/spreadsheets/d/1cEBKwKAyWEj4D_buSPGmYz-ZukQl4dXslpjwqyVEYfo/edit?usp=sharing

Follow the pattern used by @anbud in #3

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

done in #25
