### ISSUE TITLE
Problem: users can't update applications

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/emurpas#249]
I don't know if this is intentional or how it fits into the existing workflow, but we should at least support "prefilling" a new application based on an old application.

**Comment by gazhayes** [comment]
It's ok actually, we may end up needing to pull applications from upstream (a platform called f6s) so this may end up not being a problem

**Comment by porcellus** [comment]
Users can actually edit their applications if they remove the /view from the end of the URL when the view the application. My concern was the while we allow editing it by messing with the URL we don't allow it by normal UI interaction.

**Comment by gazhayes** [comment]
oh ok yeah may as well add it to the UI then

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
So editing is not a problem? This way users can edit applications after they have been reviewed. We can disallow it and (maybe) allow updates by invalidating + cloning.

**Comment by gazhayes** [comment]
Oh, hmmm, no actually editing should not be allowed then. They can comment on questions from reviewers already which should be enough. So I guess just make sure editing is not possible once submitted.

**Comment by porcellus** [comment]
@emurgobot done in #252
