### ISSUE TITLE
problem: Completing new application not redirecting user to new page

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#33]
problem: when user completes the final step, user is not redirected to a seperate page or notified that the process has been complete.

solution: redirect user to a different page possibly `completed` applications, notify user that the process is complete and destroy wizard. save wizard progress as complete

**Comment by samuelralak** [comment]
not added any new views. waiting on changes from #34

**Comment by AshHimself** [comment]
PR inbound shortly
