### ISSUE TITLE
problem: user cannot view in-progress forms

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#34]
problem: without knowing the application id, there is no way for users to view their in-progress application forms.

solution: create an `in progress` page where user can access saved or in-progress application forms

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@samuelralak - what do you mean without knowing the id? you can view it now? what view?

**Comment by samuelralak** [comment]
@AshHimself when user creates a new application, a unique id is created which is then used to track subsequent application steps i.e `http://emurpas.org/applications/32fWn2And3PRy6Se5` in this case the id is `32fWn2And3PRy6Se5`. As it is now, without the user knowing this id, there is no way for the user to resume progress if by any chance he/she navigates away from the wizard.

**Comment by AshHimself** [comment]
@samuelralak - Do you have a flag to imply that an application is complete and no longer in progress?

**Comment by AshHimself** [comment]
I suppose I could check if team members exist then an application is considered 'in progress'

**Comment by AshHimself** [comment]
Fixed in #48
@emurgobot label "done"
@emurgobot done

@samuelralak - thinking we need a way to view completed applications as well? Viewing in progress works for viewing completed was not working for me.

**Comment by samuelralak** [comment]
yes, we can actually do that with what we already have. will create an issue in a bit to build upon this.

@gazhayes will users be allowed to have multiple project applications?

**Comment by samuelralak** [comment]
nop. its no longer needed. if any modifications will be required in future,
we could always open another issue.

**Comment by gazhayes** [comment]
> will users be allowed to have multiple project applications?
 
Definitely not

**Comment by samuelralak** [comment]
@gazheyes i’ll create an issue for that patch
