### ISSUE TITLE
problem: can not see saved applications

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/Emurpas#39]
problem: can not see saved applications, i've saved one, it exists in MongoDB but my homepage is EMPTY!!!

solution: tbc

**Comment by samuelralak** [comment]
@AshHimself logged this one already #34

**Comment by AshHimself** [comment]
oops, already started fixing, have you? I claimed other. let me know and i'll

**Comment by samuelralak** [comment]
no worries. I haven’t touched it.

**Comment by AshHimself** [comment]
Duplicate
