### ISSUE TITLE
Problem: coreUI not used

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#4]
Problem: coreUI not used

Solution: implement coreUI.

**Comment by gazhayes** [comment]
ping @samuelralak

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
I think a different color per application will offer some sorta brand and
easy identification between all of them.

**Comment by gazhayes** [comment]
Hmmm, I guess a different colour scheme just to distinguish it a bit.

**Comment by samuelralak** [comment]
agreed

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
@anbud this guy here @emurgobot is still not responding

**Comment by anbud** [comment]
I'll check it out. :)

**Comment by anbud** [comment]
@emurgobot remove "done"

**Comment by anbud** [comment]
@emurgobot remove "done"

**Comment by anbud** [comment]
@gazhayes, did you happen to change @emurgobot's password? I've checked the logs, and it's saying that provided credentials are invalid.

**Comment by gazhayes** [comment]
Oh damn, yes I did. Oops. I'll fix it up.

**Comment by gazhayes** [comment]
@anbud I fixed the password
