### ISSUE TITLE
problem: emurgobot is unresponsive

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#40]
problem: our friend @emurgobot doesn't seem to work on emurpas. not sure if this issue is only limited to emurpas - calling @emurgobot commands here don't seem to do anything. must be asleep.

ping @gazhayes

**Comment by AshHimself** [comment]
@gazhayes is sipping on cocktails on some island still. He doesn't care about bots :D

**Comment by gazhayes** [comment]
I'm.... I'm not, I swear!

**Comment by samuelralak** [comment]
lol, we believe you mate

**Comment by gazhayes** [comment]
The VPS probably expired, I'll just move it to our emurgo infrastructure instead.

**Comment by gazhayes** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
WTF it was working before

**Comment by anbud** [comment]
This one is done.

@emurgobot label "done"
