### ISSUE TITLE
Problem: clicking on saved applications in home is unresponsive

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#49]
Problem: The homepage currently lists all saved applications but there is currently now way  for users to resume the application progress. Clicking on the saved application in home doesn't do anything.

Solution: List applications with their respective statuses - whether incomplete or in progress - and render a button or link that would:
- resume application if incomplete 
- view application if completed

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
dang it, I did have this working but when I added the resume button I removed it but forgot to put it back in :)

**Comment by samuelralak** [comment]
done in #60
