### ISSUE TITLE
problem: moderators cannot view applications

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#73]
problem: moderators cannot view applications

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Hey @samuelralak how are you going with this one?

**Comment by samuelralak** [comment]
@gazhayes submitting a PR later on today.

**Comment by samuelralak** [comment]
@emurgobot done

**Comment by samuelralak** [comment]
done in #74
