### ISSUE TITLE
problem: moderators cannot promote new moderators

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#75]
problem: moderators cannot promote new moderators

solution: I guess the simplest solution right now is to list all users by username and email and allow anyone with moderator privileges to promote anyone else.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
someone had already sneaked this feature in. made a few modifications

**Comment by samuelralak** [comment]
@emurgobot done

done in #77
