### ISSUE TITLE
problem: step 4 in the application process isn't working

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#76]
problem: step 4 in the application process isn't working. Users can get to step 3 but cannot go any further. I haven't done any debugging.

**Comment by geekyd** [comment]
@gazhayes It is working for me locally.

**Comment by samuelralak** [comment]
Investigating this @emurgobot claim

**Comment by samuelralak** [comment]
seems to be working fine online. we can wait and see if anyone else is experiencing the same

**Comment by samuelralak** [comment]
@emurgobot unclaim

**Comment by anbud** [comment]
Works for me as well, both on prod and locally.

**Comment by gazhayes** [comment]
weird
