### ISSUE TITLE
problem: bootstrap version has vulnerabilites

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#78]
problem: bootstrap version by coreui is outdated and has vulnerabilites

solution: update coreui version

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Can you check all repos for this?

**Comment by samuelralak** [comment]
@gazhayes yes, checking

**Comment by samuelralak** [comment]
@emurgobot done

done in #79
