### ISSUE TITLE
problem: maintainers cannot rate responses 

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurpas#80]
problem: maintainers cannot rate responses 

solution: allow maintainers to rate each response to each question from 1 to 10. Any number of maintainers should be able to rate each response independently. The ratings should be displayed to other maintainers as well as the applicant.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

done in #81
