### ISSUE TITLE
problem: self-populating questions not working

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#83]
problem: there are self-populating questions based on the answers given in the radio button list, but these questions are not being updated. I haven't checked, but I'm guessing the code is still there and it's just a UI issue.

<img width="838" alt="screenshot 2018-11-05 at 4 10 10 pm" src="https://user-images.githubusercontent.com/8143945/47985768-b4e0e300-e115-11e8-805d-7644b08c14cb.png">

**Comment by MadanBhandari** [comment]
I'll look into this :)

@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #85
