### ISSUE TITLE
Problem : emurgobot is not working on this repo

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurpas#84]
Problem : emurgobot is not working on this repo

ping @gazhayes @anbud

**Comment by anbud** [comment]
I'll fix it.

**Comment by anbud** [comment]
@emurgobot label "in progress"

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
I'm not really sure what happened, but turning it off and on again helped. :D

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done

**Comment by MadanBhandari** [comment]
Looks like it's working as expected
