### ISSUE TITLE
problem: users shown incorrect text on form completion 

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#88]
problem: users shown incorrect text on form completion 

This view is shown to users after completing their personal information.

<img width="890" alt="screenshot 2018-11-07 at 5 39 46 pm" src="https://user-images.githubusercontent.com/8143945/48123208-4e45fb80-e2b4-11e8-873e-0d8cbbd9d546.png">

solution: don't show this text if user has submitted their personal info form.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #94.

@emurgobot done
