### ISSUE TITLE
problem: users can still access personal form after submitting it

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#89]
problem: users can still access personal form after they've completed and submitted the form. 

<img width="769" alt="screenshot 2018-11-07 at 5 42 51 pm" src="https://user-images.githubusercontent.com/8143945/48123411-cca29d80-e2b4-11e8-877a-5630a02bf545.png">

**Comment by geekyd** [comment]
@emurgobot claiim

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #92 
@emurgobot done
