### ISSUE TITLE
Problem: no logo for Emurpas

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurpas#9]
Problem: Emurpas does not have a logo. Need one that blends with the Emurpas UI.

ping @gazhayes

**Comment by gazhayes** [comment]
Claim

**Comment by gazhayes** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@emurgobot done

**Comment by gazhayes** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
sweet. adding it to the Project
