### ISSUE TITLE
problem: logged out users can see private information

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#95]
problem: logged out users can see private information

<img width="1487" alt="screenshot 2018-11-08 at 12 05 59 pm" src="https://user-images.githubusercontent.com/8143945/48177410-5f901600-e34f-11e8-8a66-b1807031c146.png">

solution: only moderators should be able to see this kind of information

**Comment by MadanBhandari** [comment]
I am only getting this on log out users : 

![emurpas-error](https://user-images.githubusercontent.com/6429311/48188997-164ac100-e365-11e8-8ea1-510b3f01c221.png)

May be #98 has something to do with my system :/

**Comment by gazhayes** [comment]
On production or local?

**Comment by MadanBhandari** [comment]
@anbud only checking logged-in user before subscription seems to working.

**Comment by MadanBhandari** [comment]
@emurgobot done in #114
