### ISSUE TITLE
problem: moderators cannot ask questions about application

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/emurpas#97]
problem: moderators cannot ask questions about application. This is a problem because moderators will often need more information or clarification from the users who are associated with a project.

**Comment by anbud** [comment]
I'll do this one as a part of #96. I plan to create an universal commenting system on applications/application fields, and this can easily be added as a part of that.

@emurgobot claim

**Comment by anbud** [comment]
Done in #99.

@emurgobot done
