### ISSUE TITLE
Problem : User is not able to login/Signup

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurpas#98]
Is this just me or every one getting this ?

I am getting following error on console.

> I20181108-14:40:05.519(5.5)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"$or":[{"createdBy":null},{}]}
> I20181108-14:40:05.558(5.5)?     at packages/mongo/oplog_observe_driver.js:881:15
> I20181108-14:40:05.558(5.5)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:733:12)
> I20181108-14:40:05.558(5.5)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
> I20181108-14:40:05.558(5.5)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
> I20181108-14:40:05.559(5.5)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
> I20181108-14:40:05.559(5.5)?     at packages/mongo/oplog_observe_driver.js:191:10
> I20181108-14:40:05.559(5.5)?     at packages/mongo/oplog_observe_driver.js:15:9
> I20181108-14:40:05.559(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
> I20181108-14:40:05.559(5.5)?     at packages/meteor.js:505:25
> I20181108-14:40:05.559(5.5)?     at runWithEnvironment (packages/meteor.js:1241:24)

If you have already logged in user, log out and then sign up for another account.

ping @anbud @gazhayes

**Comment by gazhayes** [comment]
Is that on production or local?

**Comment by MadanBhandari** [comment]
> Is that on production or local?

On local development

**Comment by gazhayes** [comment]
Ah ok, in that case it could be anything. Are you using Windows? Try nuking the database and see what happens.

**Comment by MadanBhandari** [comment]
I tried by updating meteor to 1.8, resetting meteor by `meteor reset`, still same issue

I am also getting same error on `meteor run --production` as well :/

**Comment by anbud** [comment]
Hmm, everything is working fine for me locally, on Windows. I'm not sure what's causing the problem. You could try reinstalling Meteor altogether if everything else fails, it may help.

**Comment by gazhayes** [comment]
Try cloning emurpas into a new directory to eliminate any weird issues with your local copy.

If that doesn't work:
Did you try updating emurpas with the latest version of meteor, or just the version installed on your system but not emurpas itself?

**Comment by geekyd** [comment]
Works for me on both linux & macOs. @MadanBhandari Also make sure that you are using a correct mongo database. I faced similar issues while using incorrect `MONGO_URL`

**Comment by anbud** [comment]
@MadanBhandari, I believe that #115 should fix this issue for you. I've managed to reproduce it, I believe I've fixed the root cause there.

**Comment by MadanBhandari** [comment]
Yes, this is resolved now. btw what's the cause @anbud ?
